<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHTGGdwp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHTGGdwp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHTGGdwp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHTGGdwp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHTGGdwp\App_KernelDevDebugContainer([
    'container.build_hash' => 'HTGGdwp',
    'container.build_id' => 'd3780043',
    'container.build_time' => 1708785197,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHTGGdwp');
